.TH major 7 "Linux User's Resume" "August 2011" "Linux User's Resume"
.IP
.SH NAME
.PP
Major Hayden - a social nerd
.SH SYNOPSIS
.PP
major [\[em]admin systems|database] [\[em]developer] [\[em]educator]
[\[em]leader] [\[em]other]
.SH SUMMARY
.PP
I'm a systems administrator with skills in database administration and application development. I enjoy connecting people with technology solutions that are easy to use, affordable, and sustainable over time.
.SH OPTIONS
.PP
\fB\-\-admin systems\fR
.PP
.RS
Extensive experience with the configuration, hardening, and maintenance of various Linux distributions, including:
.PP
* Red Hat Enterprise Linux, Fedora, CentOS
.PD 0
.P
.PD
* Debian, Ubuntu
.PD 0
.P
.PD
* Gentoo
.PP
Comfortable working with open source Xen and Xen Server installations in large-scale environments. Able to customize and patch upstream pv-ops kernels for use with Xen and also familiar with the preparation and maintenance of base images for Xen guests.
.PP
Responsible for providing direct customer support for shared and dedicated hosting environments via telephone, tickets, and online chat. Familiar with configuration file management via puppet.
.PP
Currently a Red Hat Certified Engineer in versions 4 (http://wewt.me/9z) and 5 (http://rkrh.kr/ze). Also obtained a Certificate of Expertise in Systems Monitoring & Performance Tuning (EX442) and Red Hat Enterprise Storage Management (EX436) in the RHCA track of exams.
.RE
.PP
\fB\-\-admin database\fR
.PP
.RS
Skilled in MySQL database administration for standalone servers as well as replicated and clustered environments. Authored MySQLTuner (http://mysqltuner.com/) in an effort to efficiently optimize database servers based on their specific workloads.
.PP
Currently a Certified MySQL Database Administrator.
.RE
.PP
\fB\-\-developer\fR
.PP
.RS
Familiar with PHP, Perl, Ruby and shell scripting.
.RE
.PP
\fB\-\-educator\fR
.RS
Started multiple projects to share knowledge and assist other technical people:
.PP
* Racker Hacker (http://rackerhacker.com/) - words of wisdom from a server administrator
.PD 0
.P
.PD
* Plesk Hacker (http://pleskhacker.com/) - detailed documentation of the Plesk database
.PD 0
.P
.PD
* icanhazip (http://icanhazip.com/) - simple public IP detection
.PD 1
.P
.PD
* MySQL Tuner (http://mysqltuner.com/) - high-performance MySQL tuning
script
.PD 0
.P
.PD
* rkrh.kr (http://rkrh.kr/) - my personal URL shortener
.PP
Compiled and taught classes covering various systems administration topics including MySQL database administration, SSL certificates, and server security.
.RE
.PP
\fB\-\-leader\fR
.RS
.PP
Comfortable leading groups of technical people in customer-facing environments. Also able to provide individualized mentoring on technical and career development topics.
.RE
.PP
\fB\-\-other\fR
.RS
.PP
Currently certified as an Emergency Medical Technician in Texas.
.RE
.SH HISTORY
.PP
* Rackspace (http://rackspace.com/)
.RS
- Linux Systems Administrator
.PD 0
.P
.PD
- Senior Systems Engineer
.PD 0
.P
.PD
- Lead Operations Engineer, Cloud Servers
.RE
.PP
* SecureTrust Corporation
.PD 0
.P
.PD
  (now a wholly owned subsidiary of Trustwave Holdings,
Inc. (http://trustwave.com/))
.RS
- VP of Operations
.PD 0
.P
.PD
- Lead Developer
.RE
.PP
* American Medical Response (http://www.amr.net/)
.RS
- Field Medic / EMT
.RE
.SH SEE ALSO
.PP
* E-mail: major at mhtx dot net
.PD 0
.P
.PD
* Phone: 210.370.7667
.PD 0
.P
.PD
* Twitter: @rackerhacker (http://twitter.com/rackerhacker)
.PD 0
.P
.PD
* IRC: rackerhacker on irc.freenode.net
.IP
.PP
© 2011 Major Hayden